### ISSUE TITLE
Elastalert doesnt work

### ISSUE THREAD

**Issue by srolskyi** [bitsensor/elastalert#46]
Hello,
I have:
1. kibana - 6.3.1
2. ES - 6.3.0
3. elastalert latest
I run service like this:
```
docker run -d -p 3030:3030 \
    -v `pwd`/config/elastalert.yaml:/opt/elastalert/config.yaml \
    -v `pwd`/config/config.json:/opt/elastalert-server/config/config.json \
    -v `pwd`/rules:/opt/elastalert/rules \
    -v `pwd`/rule_templates:/opt/elastalert/rule_templates \
    --net="host" \
    --name elastalert bitsensor/elastalert:latest
```
I saw:

```
09:35:43.889Z  INFO elastalert-server:
    ProcessController:  Elastic Version:6
    Mapping used for string:{'type': 'keyword'}
    New index elastalert_status created
    Done!
```
six indexes was created. Then I  install "elastalert" kibana plugins, restart kibana and see your plugin on kibana.
Created rule, but it doesn't work. On docker container logs I only see:
```
09:19:37.712Z ERROR elastalert-server:
    ProcessController:  INFO:elastalert:Sleeping for 299.988677 seconds
    
09:24:37.811Z ERROR elastalert-server:
    ProcessController:  INFO:elastalert:Sleeping for 299.990961 seconds
    
09:29:37.826Z ERROR elastalert-server:
    ProcessController:  INFO:elastalert:Sleeping for 299.991725 seconds
    
09:34:37.881Z ERROR elastalert-server:
    ProcessController:  INFO:elastalert:Sleeping for 299.993885 seconds
```
I check: GET /status and got:
{"status":"READY"}

Tried restart service, container etc.. all time the same ERROR.
How I can get more logs?

**Comment by martijnrondeel** [comment]
Please try the latest version of the Kibana plugin and ElastAlert and let me know if the issue still persists.

**Comment by srolskyi** [comment]
After update kibana-plugin and ElastAlert I got the same error.
API works.
when I try test: http://localhost:3030/metadata/elastalert_status
I got: {"error":{"message":"No Living connections"}}

```
alert_1   |   Error: Request error, retrying
alert_1   |   POST http://elastalert:9200/elastalert_status/elastalert_status/_search => getaddrinfo ENOTFOUND elastalert elastalert:9200
alert_1   |       at Log.error (/opt/elastalert-server/node_modules/elasticsearch/src/lib/log.js:226:56)
alert_1   |       at checkRespForFailure (/opt/elastalert-server/node_modules/elasticsearch/src/lib/transport.js:259:18)
alert_1   |       at HttpConnector.<anonymous> (/opt/elastalert-server/node_modules/elasticsearch/src/lib/connectors/http.js:163:7)
alert_1   |       at ClientRequest.wrapper (/opt/elastalert-server/node_modules/lodash/lodash.js:4935:19)
alert_1   |       at ClientRequest.emit (events.js:182:13)
alert_1   |       at Socket.socketErrorListener (_http_client.js:391:9)
alert_1   |       at Socket.emit (events.js:182:13)
alert_1   |       at emitErrorNT (internal/streams/destroy.js:82:8)
alert_1   |       at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
alert_1   |       at process._tickCallback (internal/process/next_tick.js:63:19)
alert_1   | 
alert_1   | Elasticsearch WARNING: 2018-09-25T08:35:16Z
alert_1   |   Unable to revive connection: http://elastalert:9200/
```
In file: config.yaml I set:
es_host: es-myhost
es_port: 9200

after start index was created success, why elastalert try to connect elastalert:9200?

**Comment by martijnrondeel** [comment]
`es_host` should point to your ElasticSearch instance, not ElastAlert. If you run ElastAlert somewhere else you'd have to change that in the Kibana plugin, see the [docs](https://github.com/bitsensor/elastalert-kibana-plugin#configuration).

**Comment by srolskyi** [comment]
I know it. es_host point to elasticsearch.
Why indexes "elastalert_status*" was created for my elasticsearch, but if I use api i see no living connection

**Comment by martijnrondeel** [comment]
Ah ok. Are you running ElasticSearch on the same machine as the ElastAlert server? If so please try changing `es_host` to `es_host: localhost`.

**Comment by srolskyi** [comment]
Problem with "No living connection" solved. :)
I created rule on kibana plugins menu, but nothing happens:
Every 5 min I see:
```
alert_1   | 09:25:02.519Z ERROR elastalert-server:
alert_1   |     ProcessController:  INFO:elastalert:Sleeping for 299.988452 seconds
```

How I can see more logs?
I change "es_debug":  to "false" or "true" on file config.json but still get the same message on the console.

**Comment by martijnrondeel** [comment]
I've pushed a new version, [0.0.14](https://github.com/bitsensor/elastalert/releases/tag/0.0.14).

If you are using a different host for ElasticSearch other than `localhost:9200` you will have to change this in two places now (`config.yaml` and `config.json`). I know this is rather inconvenient, I'll improve this in the future.

Let me know if this fixes your issue.

**Comment by srolskyi** [comment]
I use docker, and elasticsearch not located on localhost.
btw, elastalert knows my elasticsearch host. I go into "elastalert" container:
`docker exec -ti  alert_1 /bin/sh`
then I do:
`curl elasticsearch:9200`
I got:
```
{
  "name" : "V36KNsu",
  "cluster_name" : "MY-CLUSTER",
  "cluster_uuid" : "asdv6WK43saGGcksFHWL5MvA",
  "version" : {
    "number" : "6.3.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "424e937",
    "build_date" : "2018-06-11T23:38:03.357887Z",
    "build_snapshot" : false,
    "lucene_version" : "7.3.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
I updated version to 0.0.14 but it still doesn't work for me...

**Comment by martijnrondeel** [comment]
Please post your `config/elastalert.yaml` and `config/config.json` files here.

**Comment by srolskyi** [comment]
1. config/elastalert.yaml
```
rules_folder: /opt/rules
run_every:
 minutes: 5

buffer_time:
  minutes: 5

es_host: elastalert
es_port: 9200

writeback_index: elastalert_status
alert_time_limit:
  days: 2
```

2. config/config.json
```
{
  "appName": "elastalert-server",
  "port": 3030,
  "elastalertPath": "/opt/elastalert",
  "verbose": true,
  "es_debug": true,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "elastalert",
  "es_port": 9200,
  "writeback_index": "elastalert_status"
}
```

**Comment by martijnrondeel** [comment]
Are you still having issues @srolskyi or did you manage to resolve it?
